$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    pagination:false,
    autoplay:0.1,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:2
        },
        700:{
            items:2
        },
        1000:{
            items:4
        }
    }
})